export type Member={cardNo:string;name:string;dob:string;gender:string;company:string;policyNo:string;plan:string;relation:string;active:boolean;faskes1:string;providerCategory:string;roomClass:string;annualLimit:number;remainingLimit:number};
export const members:Member[]=[
{cardNo:"MC10000001",name:"Andi Pratama",dob:"1988-04-12",gender:"Laki-laki",company:"PT Pertamina Patra Niaga",policyNo:"POL-MC-2026-001",plan:"Managed Care Gold",relation:"Karyawan",active:true,faskes1:"Klinik Pratama Sehat Sentosa",providerCategory:"Klinik",roomClass:"Kelas 1",annualLimit:75000000,remainingLimit:68450000},
{cardNo:"MC10000002",name:"Siti Rahmawati",dob:"1991-11-03",gender:"Perempuan",company:"PT Kilang Pertamina Internasional",policyNo:"POL-MC-2026-002",plan:"Managed Care Gold",relation:"Karyawan",active:true,faskes1:"RS Hermina Kemayoran",providerCategory:"Rumah Sakit",roomClass:"Kelas 1",annualLimit:75000000,remainingLimit:72100000},
{cardNo:"MC10000003",name:"Budi Santoso",dob:"1985-07-22",gender:"Laki-laki",company:"PT Pertamina Hulu Energi",policyNo:"POL-MC-2026-003",plan:"Managed Care Platinum",relation:"Karyawan",active:true,faskes1:"RS Pusat Pertamina",providerCategory:"Rumah Sakit",roomClass:"VIP",annualLimit:125000000,remainingLimit:111250000},
{cardNo:"MC10000004",name:"Maria Lestari",dob:"1993-02-17",gender:"Perempuan",company:"PT Pertamina (Persero)",policyNo:"POL-MC-2026-004",plan:"Managed Care Silver",relation:"Pasangan",active:true,faskes1:"Klinik Pertamedika Depok",providerCategory:"Klinik",roomClass:"Kelas 2",annualLimit:50000000,remainingLimit:49300000},
{cardNo:"MC10000005",name:"Raka Wijaya",dob:"2012-09-09",gender:"Laki-laki",company:"PT Pertamina Patra Niaga",policyNo:"POL-MC-2026-001",plan:"Managed Care Gold",relation:"Anak",active:true,faskes1:"Klinik Pratama Sehat Sentosa",providerCategory:"Klinik",roomClass:"Kelas 1",annualLimit:75000000,remainingLimit:74750000},
{cardNo:"MC10000006",name:"Dewi Anggraini",dob:"1979-12-28",gender:"Perempuan",company:"PT Pertamina Hulu Energi",policyNo:"POL-MC-2026-003",plan:"Managed Care Platinum",relation:"Karyawan",active:false,faskes1:"RS Pusat Pertamina",providerCategory:"Rumah Sakit",roomClass:"VIP",annualLimit:125000000,remainingLimit:125000000}
];
export const providerCategories=["Rumah Sakit","Klinik","Puskesmas/FKTP","Dokter Praktik","Dokter Gigi","Laboratorium","Apotek"];
export const urgencyReasons=["Kecelakaan","Kondisi akut / kegawatdaruratan","Di luar area Faskes 1","Faskes 1 tidak beroperasi","Emergency gigi - dokter gigi umum","Kondisi on-site di lokasi kerja","Lainnya"];
export const treatmentTypes=["Konsultasi","Laboratorium","Radiologi/Diagnostik","Tindakan Medis","Obat","Alat Kesehatan","Lainnya"];
export const claimStatuses=["Draft","Submitted","Under Verification","Need Confirmation","Approved","Partially Approved","Rejected","Scheduled for Payment","Paid"];
